In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("./datasets/cardekho_imputated.csv")

In [3]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [6]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [7]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [11]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [12]:
X

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [13]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
15406     250000
15407     925000
15408     425000
15409    1225000
15410    1200000
Name: selling_price, Length: 15411, dtype: int64

In [14]:
X.dtypes

car_name                 str
brand                    str
model                    str
vehicle_age            int64
km_driven              int64
seller_type              str
fuel_type                str
transmission_type        str
mileage              float64
engine                 int64
max_power            float64
seats                  int64
dtype: object

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

ohe = OneHotEncoder(drop="first")
str_cat = X.select_dtypes(include=["str"]).columns

scaler = StandardScaler()
num_cat = X.select_dtypes(exclude=["str"]).columns

preprocessor = ColumnTransformer(
    transformers=[
        ("OneHotEncoder", ohe, str_cat),
        ("StandardScaler", scaler, num_cat)
    ],
    remainder="passthrough"
)

X = preprocessor.fit_transform(X)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [19]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor()

gbr_params = {
    "loss": ['squared_error', 'absolute_error', 'huber', 'quantile'],
    "learning_rate": [1, 0.1, 0.01, 0.001, 0.0001],
    "n_estimators": [50, 100, 150, 200, 250, 300],
    "criterion": ["friedman_mse", "squared_error"],
    "min_samples_split": [2, 3, 4, 5, 10],
    "max_depth": [2, 3, 4, 5, 10]    
}

random = RandomizedSearchCV(
    estimator=gbr,
    param_distributions=gbr_params,
    n_iter=100,
    cv=3,
    verbose=2,
    n_jobs=-1
)

random.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END criterion=squared_error, learning_rate=0.001, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=3, min_samples_split=5, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=log_loss, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=150; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=exponential, max_depth=10, min_samples_split=2, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=5, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, max_depth=5, min_samples_split=10, n_estimators=300; total time=  13.5s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=4, min_samples_split=2, n_estimators=250; total time=  18.2s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, max_depth=3, min_samples_split=5, n_estimators=50; total time=   1.8s
[CV] END criterion=squared_error, learning_rate=0.1, loss=quantile, max_depth=4, min_samples_split=10, n_estimators=100; total time=  14.9s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=2, min_samples_split=3, n_estimators=150; total time=   7.6s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=squared_error, max_depth=5, min_samples_split=2, n_estimators=250; total time=  13.5s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=quantile, max_depth=5, min_samples_split=2, n_estimators=50; total time=   4.1s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=5, min_samples_split=4, n_estimators=50; total time=   5.3s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=quantile, max_depth=2, min_samples_split=5, n_estimators=250; total time=   8.8s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=2, min_samples_split=4, n_estimators=200; total time=   2.6s
[CV] END criterion=friedman_mse, learning_rate=1, loss=huber, max_depth=3, min_samples_split=4, n_estimators=150; total time=   3.2s
[CV] END criterion=squared_error, learning_rate=1, loss=huber, max_depth=2, min_samples_split=5, n_estimators=100; total time=   5.7s
[CV] END criterion=friedman_mse, learning_rate=1, loss=huber, max_depth=5, min_samples_split=10, n_estimators=100; total time=   3.4s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=3, min_samples_split=2, n_estimators=50; total time=   1.1s
[CV] END criterion=friedman_mse, learning_rate=1, loss=squared_error, max_depth=4, min_samples_split=10, n_estimators=250; total time=  11.2s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=quantile, max_depth=3, min_samples_split=3, n_estimators=100; total time=   1.8s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=3, min_samples_split=10, n_estimators=200; total time=   8.1s
[CV] END criterion=friedman_mse, learning_rate=1, loss=quantile, max_depth=4, min_samples_split=5, n_estimators=50; total time=   1.1s
[CV] END criterion=friedman_mse, learning_rate=1, loss=quantile, max_depth=4, min_samples_split=5, n_estimators=50; total time=   1.2s
[CV] END criterion=squared_error, learning_rate=0.001, loss=quantile, max_depth=4, min_samples_split=2, n_estimators=250; total time=  11.5s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=10, n_estimators=150; total time=  11.4s
[CV] END criterion=squared_error, learning_rate=0.1, loss=huber, max_depth=5, min_samples_split=10, n_estimators=100; total time=   4.7s
[CV] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, max_depth=4, min_samples_split=3, n_estimators=50; total time=   6.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=250; total time=  17.9s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=huber, max_depth=2, min_samples_split=10, n_estimators=300; total time=  10.4s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=quantile, max_depth=3, min_samples_split=5, n_estimators=250; total time=   8.5s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=2, min_samples_split=5, n_estimators=300; total time=   5.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=squared_error, max_depth=2, min_samples_split=2, n_estimators=200; total time=   3.4s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=absolute_error, max_depth=10, min_samples_split=2, n_estimators=200; total time= 1.3min
[CV] END criterion=squared_error, learning_rate=0.01, loss=squared_error, max_depth=2, min_samples_split=2, n_estimators=100; total time=   6.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=absolute_error, max_depth=3, min_samples_split=5, n_estimators=150; total time=   3.5s
[CV] END criterion=friedman_mse, learning_rate=1, loss=huber, max_depth=4, min_samples_split=3, n_estimators=150; total time=  10.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=4, min_samples_split=10, n_estimators=150; total time=  11.4s[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=4, min_samples_split=5, n_estimators=250; total time=   0.1s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=3, min_samples_split=5, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=exponential, max_depth=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=log_loss, max_depth=3, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=log_loss, max_depth=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=4, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=exponential, max_depth=4, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=5, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=exponential, max_depth=10, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=log_loss, max_depth=3, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=exponential, max_depth=4, min_samples_split=5, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=log_loss, max_depth=4, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=3, min_samples_split=10, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=huber, max_depth=5, min_samples_split=2, n_estimators=100; total time=   4.5s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=huber, max_depth=3, min_samples_split=10, n_estimators=100; total time=   2.1s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=4, min_samples_split=2, n_estimators=250; total time=  16.8s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=5, min_samples_split=5, n_estimators=150; total time=  17.2s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=quantile, max_depth=2, min_samples_split=4, n_estimators=50; total time=   6.3s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=squared_error, max_depth=5, min_samples_split=4, n_estimators=100; total time=   9.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=squared_error, max_depth=5, min_samples_split=2, n_estimators=250; total time=  13.8s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=quantile, max_depth=5, min_samples_split=2, n_estimators=50; total time=   6.8s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=5, min_samples_split=4, n_estimators=50; total time=   3.7s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=quantile, max_depth=2, min_samples_split=5, n_estimators=250; total time=   8.1s
[CV] END criterion=squared_error, learning_rate=0.001, loss=absolute_error, max_depth=5, min_samples_split=3, n_estimators=200; total time=  15.4s
[CV] END criterion=friedman_mse, learning_rate=1, loss=squared_error, max_depth=4, min_samples_split=10, n_estimators=250; total time=  11.9s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=quantile, max_depth=3, min_samples_split=3, n_estimators=100; total time=   1.8s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=3, min_samples_split=10, n_estimators=200; total time=   8.2s
[CV] END criterion=friedman_mse, learning_rate=1, loss=quantile, max_depth=4, min_samples_split=5, n_estimators=50; total time=   1.1s
[CV] END criterion=squared_error, learning_rate=0.001, loss=quantile, max_depth=4, min_samples_split=2, n_estimators=250; total time=  12.1s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=10, n_estimators=150; total time=  11.9s
[CV] END criterion=squared_error, learning_rate=0.1, loss=huber, max_depth=5, min_samples_split=10, n_estimators=100; total time=   6.3s
[CV] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, max_depth=4, min_samples_split=3, n_estimators=50; total time=   5.3s
[CV] END criterion=squared_error, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=250; total time=  16.2s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=huber, max_depth=2, min_samples_split=10, n_estimators=300; total time=   9.4s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=quantile, max_depth=3, min_samples_split=5, n_estimators=250; total time=   4.8s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=4, min_samples_split=4, n_estimators=300; total time=  20.3s
[CV] END criterion=squared_error, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=100; total time=   4.5s
[CV] END criterion=friedman_mse, learning_rate=1, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=200; total time=  12.7s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=2, min_samples_split=4, n_estimators=100; total time=   2.1s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=absolute_error, max_depth=2, min_samples_split=10, n_estimators=100; total time=   4.2s
[CV] END criterion=squared_error, learning_rate=1, loss=absolute_error, max_depth=2, min_samples_split=2, n_estimators=300; total time=  12.6s
[CV] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, max_depth=4, min_samples_split=3, n_estimators=300; total time=  21.6s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=5, min_samples_split=3, n_estimators=250; total time=  23.3s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=3, min_samples_split=2, n_estimators=250; total time=  10.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=2, min_samples_split=2, n_estimators=300; total time=  11.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=4, min_samples_split=2, n_estimators=200; total time=  11.7s

RandomizedSearchCV(cv=3, estimator=GradientBoostingRegressor(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['friedman_mse',
                                                      'squared_error'],
                                        'learning_rate': [1, 0.1, 0.01, 0.001,
                                                          0.0001],
                                        'loss': ['squared_error',
                                                 'absolute_error', 'huber',
                                                 'quantile'],
                                        'max_depth': [2, 3, 4, 5, 10],
                                        'min_samples_split': [2, 3, 4, 5, 10],
                                        'n_estimators': [50, 100, 150, 200, 250,
                                                         300]},
                   verbose=2)

In [21]:
from sklearn.metrics import r2_score

y_pred = random.predict(X_test)

print(r2_score(y_test, y_pred))

0.9224052380321257
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=4, min_samples_split=4, n_estimators=50; total time=   0.2s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=3, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=3, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=10, n_estimators=150; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=4, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=4, min_samples_split=3, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=exponential, max_depth=2, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=10, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=5, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=exponential, max_depth=3, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=3, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=3, min_samples_split=10, n_estimators=200; total time=   5.7s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=huber, max_depth=10, min_samples_split=2, n_estimators=250; total time= 3.1min
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=4, min_samples_split=4, n_estimators=300; total time=  20.4s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=absolute_error, max_depth=10, min_samples_split=2, n_estimators=200; total time= 1.4min
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=2, min_samples_split=4, n_estimators=100; total time=   1.8s
[CV] END criterion=squared_error, learning_rate=0.001, loss=squared_error, max_depth=2, min_samples_split=5, n_estimators=250; total time=   5.3s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=4, min_samples_split=10, n_estimators=300; total time=  17.7s
[CV] END criterion=squared_error, learning_rate=1, loss=squared_error, max_depth=2, min_samples_split=4, n_estimators=150; total time=   2.1s
[CV] END criterion=squared_error, learning_rate=0.1, loss=quantile, max_depth=2, min_samples_split=4, n_estimators=50; total time=   3.5s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=4, min_samples_split=4, n_estimators=200; total time=  15.1s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=quantile, max_depth=4, min_samples_split=5, n_estimators=100; total time=   3.2s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=3, min_samples_split=2, n_estimators=100; total time=   7.3s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=quantile, max_depth=2, min_samples_split=5, n_estimators=100; total time=   1.5s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=squared_error, max_depth=10, min_samples_split=4, n_estimators=50; total time=  11.9s
[CV] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, max_depth=2, min_samples_split=4, n_estimators=300; total time=  10.3s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=10, min_samples_split=4, n_estimators=150; total time=  22.4s
[CV] END criterion=squared_error, learning_rate=0.001, loss=quantile, max_depth=3, min_samples_split=2, n_estimators=100; total time=   5.7s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=4, min_samples_split=5, n_estimators=250; total time=   0.1s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=log_loss, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=150; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=exponential, max_depth=10, min_samples_split=2, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=5, min_samples_split=2, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=5, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=3, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=3, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=4, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=5, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=squared_error, max_depth=5, min_samples_split=10, n_estimators=300; total time=  13.6s
[CV] END criterion=squared_error, learning_rate=1, loss=squared_error, max_depth=5, min_samples_split=2, n_estimators=100; total time=  10.5s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=5, min_samples_split=5, n_estimators=150; total time=  23.4s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=2, min_samples_split=3, n_estimators=150; total time=   7.7s
[CV] END criterion=squared_error, learning_rate=1, loss=squared_error, max_depth=10, min_samples_split=3, n_estimators=50; total time=   3.7s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=squared_error, max_depth=2, min_samples_split=10, n_estimators=300; total time=   7.8s
[CV] END criterion=squared_error, learning_rate=1, loss=huber, max_depth=5, min_samples_split=3, n_estimators=150; total time=  11.8s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=huber, max_depth=4, min_samples_split=10, n_estimators=50; total time=   6.0s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=squared_error, max_depth=2, min_samples_split=10, n_estimators=250; total time=   3.9s
[CV] END criterion=squared_error, learning_rate=0.001, loss=absolute_error, max_depth=5, min_samples_split=3, n_estimators=200; total time=  15.5s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=10, min_samples_split=5, n_estimators=50; total time=  34.2s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=absolute_error, max_depth=2, min_samples_split=2, n_estimators=250; total time=   9.3s
[CV] END criterion=squared_error, learning_rate=1, loss=absolute_error, max_depth=2, min_samples_split=10, n_estimators=200; total time=   3.2s
[CV] END criterion=squared_error, learning_rate=0.1, loss=huber, max_depth=5, min_samples_split=10, n_estimators=100; total time=   5.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=absolute_error, max_depth=4, min_samples_split=3, n_estimators=50; total time=   5.7s
[CV] END criterion=squared_error, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=250; total time=  17.4s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=squared_error, max_depth=10, min_samples_split=2, n_estimators=250; total time=  60.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=huber, max_depth=5, min_samples_split=2, n_estimators=250; total time=  32.7s
[CV] END criterion=squared_error, learning_rate=0.1, loss=absolute_error, max_depth=3, min_samples_split=10, n_estimators=200; total time=   7.4s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=10, min_samples_split=5, n_estimators=50; total time=   6.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=squared_error, max_depth=2, min_samples_split=2, n_estimators=100; total time=   5.6s
[CV] END criterion=squared_error, learning_rate=0.01, loss=squared_error, max_depth=2, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=squared_error, max_depth=3, min_samples_split=2, n_estimators=250; total time=   6.8s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=absolute_error, max_depth=4, min_samples_split=10, n_estimators=300; total time=  18.3s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=huber, max_depth=10, min_samples_split=10, n_estimators=150; total time= 1.4min
[CV] END criterion=squared_error, learning_rate=0.001, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=3, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=3, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=exponential, max_depth=2, min_samples_split=10, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=10, n_estimators=150; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=log_loss, max_depth=4, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.01, loss=log_loss, max_depth=4, min_samples_split=3, n_estimators=50; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=exponential, max_depth=2, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=3, n_estimators=300; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=log_loss, max_depth=2, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=10, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=exponential, max_depth=3, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=exponential, max_depth=3, min_samples_split=10, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=10, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=4, n_estimators=100; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=3, n_estimators=200; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=1, loss=exponential, max_depth=4, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=1, loss=exponential, max_depth=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=3, min_samples_split=10, n_estimators=200; total time=   5.8s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=huber, max_depth=10, min_samples_split=2, n_estimators=250; total time= 3.1min
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=4, min_samples_split=4, n_estimators=300; total time=  19.8s
[CV] END criterion=squared_error, learning_rate=0.01, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=100; total time=   3.4s
[CV] END criterion=friedman_mse, learning_rate=1, loss=quantile, max_depth=5, min_samples_split=4, n_estimators=200; total time=  13.3s
[CV] END criterion=squared_error, learning_rate=0.001, loss=huber, max_depth=2, min_samples_split=4, n_estimators=100; total time=   1.5s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=absolute_error, max_depth=2, min_samples_split=10, n_estimators=100; total time=   1.7s
[CV] END criterion=squared_error, learning_rate=1, loss=absolute_error, max_depth=2, min_samples_split=2, n_estimators=300; total time=  12.5s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=huber, max_depth=5, min_samples_split=2, n_estimators=250; total time=  27.1s
[CV] END criterion=squared_error, learning_rate=0.1, loss=absolute_error, max_depth=3, min_samples_split=10, n_estimators=200; total time=   9.1s
[CV] END criterion=squared_error, learning_rate=0.1, loss=squared_error, max_depth=10, min_samples_split=5, n_estimators=50; total time=  10.3s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=absolute_error, max_depth=3, min_samples_split=5, n_estimators=150; total time=   4.1s
[CV] END criterion=friedman_mse, learning_rate=1, loss=huber, max_depth=4, min_samples_split=3, n_estimators=150; total time=  11.4s
[CV] END criterion=squared_error, learning_rate=0.01, loss=huber, max_depth=4, min_samples_split=10, n_estimators=150; total time=  11.2s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=squared_error, max_depth=3, min_samples_split=10, n_estimators=300; total time=  10.6s
[CV] END criterion=squared_error, learning_rate=1, loss=absolute_error, max_depth=3, min_samples_split=2, n_estimators=100; total time=   1.5s
[CV] END criterion=squared_error, learning_rate=0.0001, loss=squared_error, max_depth=2, min_samples_split=2, n_estimators=50; total time=   1.8s
[CV] END criterion=friedman_mse, learning_rate=1, loss=huber, max_depth=5, min_samples_split=5, n_estimators=300; total time=  27.5s
[CV] END criterion=friedman_mse, learning_rate=0.0001, loss=huber, max_depth=10, min_samples_split=4, n_estimators=100; total time=  54.8s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=4, min_samples_split=5, n_estimators=250; total time=   0.1s
[CV] END criterion=friedman_mse, learning_rate=0.001, loss=exponential, max_depth=2, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.01, loss=exponential, max_depth=5, min_samples_split=5, n_estimators=150; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=10, min_samples_split=10, n_estimators=300; total time=   0.0s
[CV] END criterion=friedman_mse, learning_rate=0.1, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=250; total time=   0.0s
[CV] END criterion=squared_error, learning_rate=0.001, loss=log_loss, max_depth=3, min_samples_split=4, n_estimators=100; total time=   0.0s